"""The one place that decides what an lab artifact's buffers are called.

`UploadWeights` matches an artifact's buffers to a carrier's initializers **by
name**, and nothing checks that the two sides were generated by the same idea of
what a name is. A mismatch is not a numerical error -- it is a hard failure at
load, or worse, a silent one if two different tensors happen to agree on shape.

So the graph builder and the weight generator both read their names from here,
and neither is allowed a literal of its own. The plan for each tensor also
carries the shape and data type the buffer will declare, which is what lets the
generator produce an initializer that satisfies `ValidateInitializer` without
the builder having to be consulted.
"""

import os
from collections.abc import Iterator
from dataclasses import dataclass
from typing import Literal

from lczero_triton.lab._mapping import (
    Architecture,
    EgtBlock,
    EgtNetwork,
    EgtSite,
    EncoderBlock,
    LabNetwork,
    PairTables,
    SmolgenBlock,
)
from lczero_triton.lab._onnx import FLOAT16, FLOAT32, INT32, UINT8

# How a plan's payload is assembled from the source graph.
Source = Literal[
    "copy", "gate_pair", "gate_bias", "scalar", "integer", "fold_scaled", "fold_bias", "offsets", "relu", "constant",
    "zeros", "gate_pair_padded", "gate_bias_padded", "rows_padded", "concat_columns", "concat",
    "code_table", "code_sums", "fold_scaled_codes",
    "egt_mix_codes",  # K1
    "head_scaled", "head_scaled_constant", "egt_fold_scaled", "egt_fold_bias", "transpose",  # R0
    "filled", "quant_vector",  # Q1: a repeated constant, and one vector of the analyser's .npz
    "i8_weight", "i8_scale", "i8_bias", "d1_refit",  # Q1's integer GEMM (round 26): folded weights, D1's WDL layer
]

# CUTLASS's GEMM templates need every width to be a multiple of 8; the lab's dff 683
# is not. Padding the FFN hidden width with zero columns is exact (P1): a zero
# gate-and-up pair produces sigmoid(0) * 0 = 0 and FFN2 reads those rows through zero
# weights. The builder and the carrier both size the FFN from `padded_hidden`.
FFN_ALIGNMENT = 8

# O: how the attention output gate's projection is served. "packed": Q, K, V and G as one [width, 4 width] GEMM
# (`/mha/qkvg`, the gate read from the packed row by `attention_static`); "separate": the P3 [width, 3 width] QKV
# plus a `/mha/gate` GEMM of the same input. Read once, by the carrier and the builder alike.
_OGATE_FORMS = ("packed", "separate")
_OGATE_FORM = os.environ.get("LC0EX_OGATE_FORM", "packed")


def output_gate_form() -> str:
    """Return "packed" or "separate", refusing anything else `LC0EX_OGATE_FORM` names."""
    if _OGATE_FORM not in _OGATE_FORMS:
        message = f"LC0EX_OGATE_FORM={_OGATE_FORM!r}; expected one of {_OGATE_FORMS}"
        raise ValueError(message)
    return _OGATE_FORM


def padded_hidden(hidden: int) -> int:
    """Return the FFN hidden width rounded up to CUTLASS's alignment."""
    return -(-hidden // FFN_ALIGNMENT) * FFN_ALIGNMENT


@dataclass(frozen=True, slots=True)
class BufferPlan:
    """One artifact buffer and the source tensors that fill it."""

    name: str
    shape: tuple[int, ...]
    data_type: int
    source: Source
    tensors: tuple[str, ...]

    @property
    def element_count(self) -> int:
        """Return how many elements the declared shape holds."""
        count = 1
        for dimension in self.shape:
            count *= dimension
        return count


def _plan(
    name: str,
    shape: tuple[int, ...],
    *tensors: str,
    source: Source = "copy",
    data_type: int = FLOAT16,
) -> BufferPlan:
    """Build one plan, defaulting to a straight FP16 copy."""
    return BufferPlan(
        name=name,
        shape=shape,
        data_type=data_type,
        source=source,
        tensors=tensors,
    )


# ---------------------------------------------------------------- K1 (item E, round 20c): EGT2 prologue tables
# R0 wires these into `plan_network` (`_plan_pair`) with the names the reader recovers; the plans still take plain
# initializer names, so `tests/test_prologue_egt.py` can call them with the gcap names directly.
EGT_EDGE_CHANNELS = 34
EGT_STATE_CHANNELS = 16
# (first channel, bit count) of the code groups `/prologue/mix_codes` is folded over (`prologue_egt.CODE_GROUPS`).
EGT_CODE_GROUPS = ((0, 9), (9, 8), (17, 9), (26, 8))


def plan_prologue_egt(
    *, channel_mix: str, offset_table: str, edge_mix: str, edge_offset_table: str, relative_index: str,
) -> list[BufferPlan]:
    """Plan the five FP32 tables `prologue_egt` reads (K1).

    `D` and `T` are the pair stream's (`Z = D.E + T`), now over 34 edge channels; `p_in` and the gathered `t_off`
    seed the edge stream (`e0 = rms(p_in.E + t_off[relidx])`); `mix_codes` holds, per code of each group, the
    sums of `D` (first 16 columns) and `p_in` (last 16) over the code's bits.
    """
    tokens = 64
    rows = sum(1 << width for _, width in EGT_CODE_GROUPS)
    return [
        _plan("/prologue/channel_mix", (EGT_EDGE_CHANNELS, 16), channel_mix, data_type=FLOAT32),
        _plan("/prologue/offsets", (16, tokens, tokens), offset_table, relative_index, source="offsets",
              data_type=FLOAT32),
        _plan("/prologue/edge_mix", (EGT_EDGE_CHANNELS, EGT_STATE_CHANNELS), edge_mix, data_type=FLOAT32),
        _plan("/prologue/edge_offsets", (EGT_STATE_CHANNELS, tokens, tokens), edge_offset_table, relative_index,
              source="offsets", data_type=FLOAT32),
        _plan("/prologue/mix_codes", (rows, 16 + EGT_STATE_CHANNELS), channel_mix, edge_mix,
              source="egt_mix_codes", data_type=FLOAT32),
    ]


def encoder_prefix(index: int) -> str:
    """Return the buffer-name prefix for one encoder block."""
    return f"/encoder{index}"


# Q1: the embedding's norm, which produces block 0's attention input.
EMBEDDING_PREFIX = "/attn_body"


# Q1: "" (off), "probe" (r = 1, m = 0 -- the conversion's SHAPE, for pricing only, codes nobody reads) or a
# path to the analyser's `.npz`. Read once, here, so the carrier and the builder cannot disagree about which
# norms carry vectors.
_QUANT_PRESCALE = os.environ.get("LC0EX_QUANT_PRESCALE", "")
QUANT_PROBE = "probe"


def quant_prescale_source() -> str:
    """Where this build's quantiser vectors come from: "", "probe", or a path."""
    return _QUANT_PRESCALE


# Q1, round 26: the integer GEMM itself. "" (off: the norms' copies are only emitted, as in the 09-22 probe) or
# "int8" (the four sites of every block served by `cutlass_gemm_i8`). Needs LC0EX_QUANT_PRESCALE=<npz> with `s`.
_QUANT_GEMM = os.environ.get("LC0EX_QUANT_GEMM", "")
# Blocks whose four GEMMs stay FP16 (and whose producing norms emit no copy): "" or a list like "0,27" -- the
# K/L rows on the real artifact, and the fallback if one block misbehaves (design 09-23 §2).
_QUANT_BLOCKS_FP16 = os.environ.get("LC0EX_QUANT_BLOCKS_FP16", "")
# The D1 refit (the analyser's `d1full_W_*.npz`): the value head's WDL layer, substituted in the int8 artifact only.
_QUANT_D1 = os.environ.get("LC0EX_QUANT_D1", "")


def quant_gemm_mode() -> str:
    """"" or "int8": whether Q1's integer GEMM serves the quantised sites."""
    if _QUANT_GEMM not in ("", "int8"):
        message = f"LC0EX_QUANT_GEMM={_QUANT_GEMM!r}; expected '' or 'int8'"
        raise ValueError(message)
    if _QUANT_GEMM and quant_prescale_source() in ("", QUANT_PROBE):
        message = "LC0EX_QUANT_GEMM=int8 needs LC0EX_QUANT_PRESCALE=<the analyser's .npz> (r and s per site)"
        raise ValueError(message)
    return _QUANT_GEMM


def quant_d1_source() -> str:
    """The D1 refit file, or ""; only meaningful with the integer GEMM (the FP16 artifact never carries it)."""
    if _QUANT_D1 and not quant_gemm_mode():
        message = "LC0EX_QUANT_D1 corrects the int8 trunk; it needs LC0EX_QUANT_GEMM=int8"
        raise ValueError(message)
    return _QUANT_D1


def int8_blocks(architecture: "Architecture") -> frozenset[int]:
    """The blocks whose four GEMM sites are served int8: all of them minus LC0EX_QUANT_BLOCKS_FP16."""
    if not quant_gemm_mode():
        return frozenset()
    fp16 = {int(part) for part in _QUANT_BLOCKS_FP16.split(",") if part.strip()}
    if not fp16 <= set(range(architecture.blocks)):
        message = f"LC0EX_QUANT_BLOCKS_FP16={_QUANT_BLOCKS_FP16!r} names blocks outside 0..{architecture.blocks - 1}"
        raise ValueError(message)
    return frozenset(range(architecture.blocks)) - fp16


def i8_site_names(prefix: str) -> dict[str, str]:
    """Q1: the name stem of each int8 GEMM site of one block; `<stem>/{w,scale,bias}` are its three buffers."""
    return {
        "attn_in": f"{prefix}/mha/qkv/i8",
        "attn_out": f"{prefix}/mha/out/i8",
        "ffn_in": f"{prefix}/ffn/dense1/i8",
        "ffn_mid": f"{prefix}/ffn/dense2/i8",
    }


def i8_conversion_names(prefix: str) -> dict[str, str]:
    """Q1: the two vectors a block converts through outside a norm: the attention output (`attn_out`, a
    conversion pass) and the FFN hidden (`ffn_mid`, written by the GLU's epilogue)."""
    return {"attn_out": f"{prefix}/mha/out/i8/r", "ffn_mid": f"{prefix}/ffn/mid/i8/r"}


D1_NAMES = ("/value/dense2/w_d1", "/value/dense2/b_d1")


def quantised_norms(architecture: "Architecture") -> tuple[tuple[str, str, str, str], ...]:
    """Every norm that emits an int8 copy: `(buffer prefix, norm, analyser scope, analyser site)`.

    Post-norm only, and that is the whole ordering: the embedding's FFN norm feeds block 0's attention, each
    block's `ln1` feeds its own FFN, and each block's `ln2` feeds the NEXT block's attention -- except the last,
    whose output goes to the heads, which SPEC v2 never quantises. 28 + 27 + 1 = 56 on the flagship.
    """
    source = quant_prescale_source()
    if not source:
        return ()
    if architecture.block_style != "postnorm":
        message = (f"LC0EX_QUANT_PRESCALE with a {architecture.block_style} net: under pre-norm a norm feeds only "
                   "its GEMM, so the copy replaces the FP16 output instead of joining it and the vector folds "
                   "into the norm's own scale. That road is not built (ruling 09-22 ask 4).")
        raise ValueError(message)
    norms = [(EMBEDDING_PREFIX, "ln1", "encoder0", "attn_in")]
    for index in range(architecture.blocks):
        norms.append((encoder_prefix(index), "ln1", f"encoder{index}", "ffn_in"))
        if index + 1 < architecture.blocks:
            norms.append((encoder_prefix(index), "ln2", f"encoder{index + 1}", "attn_in"))
    if source == QUANT_PROBE:
        return tuple(norms)
    from lczero_triton.lab._quant import prescale_for  # noqa: PLC0415  # a cycle otherwise: _quant reads this file.

    loaded = prescale_for(source, blocks=architecture.blocks, widths={
        "ffn_in": architecture.d_model, "attn_in": architecture.d_model,
        "ffn_mid": architecture.ffn_hidden, "attn_out": architecture.heads * architecture.head_dim})
    if quant_gemm_mode():
        # Q1: a norm emits a copy only for an int8 block -- the one whose attention (the scope's block) or FFN
        # consumes it -- and every int8 block needs all four sites, or it is served by guesswork.
        served = int8_blocks(architecture)
        for index in sorted(served):
            missing = [site for site in ("attn_in", "attn_out", "ffn_in", "ffn_mid")
                       if loaded.get(f"encoder{index}", site) is None]
            if missing:
                message = (f"LC0EX_QUANT_GEMM=int8: encoder{index} lacks {missing} in {source}; serve that block FP16 "
                           "with LC0EX_QUANT_BLOCKS_FP16 or supply the vectors")
                raise ValueError(message)
        norms = [entry for entry in norms if int(entry[2][len("encoder"):]) in served]
    return tuple(entry for entry in norms if loaded.get(entry[2], entry[3]) is not None)


def quant_names(prefix: str, norm: str) -> tuple[str, str]:
    """Q1: the prescale and offset buffers of one quantised norm, `<prefix>/<norm>/quant/{r,m}`.

    Named after the norm that EMITS the int8 copy, not after the site that consumes it. Under post-norm
    `ln1`'s output is the FFN's input and `ln2`'s output is the *next* block's attention input, so the
    analyser's `encoder<i>/attn_in` vector belongs to `/encoder<i-1>/ln2` (and to `/attn_body/ln1` at
    i = 0). `lab/_quant.producing_norm` is the one place that resolves that shift.
    """
    return (f"{prefix}/{norm}/quant/r", f"{prefix}/{norm}/quant/m")


def _plan_quant(network: LabNetwork) -> Iterator[BufferPlan]:
    """Q1: the two [d_model] FP32 vectors each quantised norm reads (460 kB on the flagship)."""
    shape = network.architecture
    probe = quant_prescale_source() == QUANT_PROBE
    for prefix, norm, scope, site in quantised_norms(shape):
        prescale, offset = quant_names(prefix, norm)
        if probe:
            yield _plan(prescale, (shape.d_model,), "1.0", source="filled", data_type=FLOAT32)
            yield _plan(offset, (shape.d_model,), "0.0", source="filled", data_type=FLOAT32)
        else:
            yield _plan(prescale, (shape.d_model,), scope, site, "r", source="quant_vector", data_type=FLOAT32)
            yield _plan(offset, (shape.d_model,), scope, site, "m", source="quant_vector", data_type=FLOAT32)


def _plan_i8_site(  # noqa: PLR0913
    stem: str, scope: str, site: str, layout: str, alpha: str, weights: tuple[str, ...], biases: tuple[str, ...],
    *, columns: int, reduction: int,
) -> Iterator[BufferPlan]:
    """Q1: one int8 GEMM site -- `[columns, reduction]` int8 weights (K-contiguous) and two FP32 [columns] vectors.

    `layout` is "concat" (the weights' output columns side by side, as the FP16 plans) or "glu_pairs" (gate and up
    interleaved column by column, `[g0 u0 g1 u1 ...]`, which is what lets one epilogue fragment hold whole pairs).
    `alpha` names the block's residual scale (folded into scale and bias) or is "" for a site without one.
    """
    head = (scope, site, layout, alpha)
    yield _plan(f"{stem}/w", (columns, reduction), *head, *weights, source="i8_weight", data_type=UINT8)
    yield _plan(f"{stem}/scale", (columns,), *head, *weights, source="i8_scale", data_type=FLOAT32)
    yield _plan(f"{stem}/bias", (columns,), layout, alpha, *biases, source="i8_bias", data_type=FLOAT32)


def _plan_quant_gemm(network: LabNetwork) -> Iterator[BufferPlan]:
    """Q1 (round 26): every int8 site's weights and vectors, the two in-block conversion vectors, and D1."""
    shape = network.architecture
    served = int8_blocks(shape)
    if not served:
        return
    if shape.block_style != "postnorm":
        message = "LC0EX_QUANT_GEMM=int8 is built for the post-norm family (the flagship); pre-norm is ask 4"
        raise ValueError(message)
    width, hidden = shape.d_model, shape.ffn_hidden
    if padded_hidden(hidden) != hidden or hidden % 16 or width % 16:
        message = f"int8 GEMM sites need d_model and dff multiples of 16; got {width} and {hidden}"
        raise ValueError(message)
    for index in sorted(served):
        block = network.blocks[index]
        prefix, scope = encoder_prefix(index), f"encoder{index}"
        stems, conversions = i8_site_names(prefix), i8_conversion_names(prefix)
        yield from _plan_i8_site(stems["attn_in"], scope, "attn_in", "concat", "",
                                 (block.query_weight, block.key_weight, block.value_weight),
                                 (block.query_bias, block.key_bias, block.value_bias),
                                 columns=3 * width, reduction=width)
        yield from _plan_i8_site(stems["attn_out"], scope, "attn_out", "concat", block.attention_alpha,
                                 (block.output_weight,), (block.output_bias,), columns=width, reduction=width)
        yield _plan(conversions["attn_out"], (width,), scope, "attn_out", "r", source="quant_vector",
                    data_type=FLOAT32)
        # The gate projection has no bias in this family (see `_plan_gated_ffn`): its half of the pairs is zero.
        yield from _plan_i8_site(stems["ffn_in"], scope, "ffn_in", "glu_pairs", "",
                                 (block.ffn_gate_weight, block.ffn_up_weight), (block.ffn_up_bias,),
                                 columns=2 * hidden, reduction=width)
        yield _plan(conversions["ffn_mid"], (hidden,), scope, "ffn_mid", "r", source="quant_vector",
                    data_type=FLOAT32)
        yield from _plan_i8_site(stems["ffn_mid"], scope, "ffn_mid", "concat", block.ffn_alpha,
                                 (block.ffn_down_weight,), (block.ffn_down_bias,), columns=width, reduction=hidden)
    if quant_d1_source():
        # FP16 like the layer it replaces (the same dense kernel reads it); FP16 rounds the refit's O(1e-3) moves
        # no worse than it rounds the trained layer.
        yield _plan(D1_NAMES[0], (128, 3), "W", network.heads.value_output_weight, source="d1_refit")
        yield _plan(D1_NAMES[1], (3,), "b", network.heads.value_output_bias, source="d1_refit")


def plan_network(network: LabNetwork) -> list[BufferPlan]:
    """Return every buffer the lab artifact declares, in build order."""
    return [
        *_plan_embedding(network),
        *_plan_pair(network),
        *_plan_encoders(network),
        *_plan_final_norm(network),
        *_plan_heads(network),
        *_plan_quant(network),
        *_plan_quant_gemm(network),
    ]


def _plan_final_norm(network: LabNetwork) -> Iterator[BufferPlan]:
    """Plan the pre-norm tower's closing norm (O); nothing on a post-norm export."""
    if network.final_norm is None:
        return
    width = network.architecture.d_model
    yield _plan("/encoder/final_norm/scale", (width,), network.final_norm.scale)
    yield _plan("/encoder/final_norm/bias", (width,), network.final_norm.bias)


def _plan_embedding(network: LabNetwork) -> Iterator[BufferPlan]:
    """Plan the input embedding, its multiplicative gate and its gated FFN."""
    embedding = network.embedding
    shape = network.architecture
    tokens, width = shape.tokens, shape.d_model
    hidden = shape.embedding_ffn_hidden
    # The preprocessing projection reads the twelve piece planes of one position
    # and writes an embedding for every square at once, so its output is the
    # flattened [tokens, dense] rather than a per-square width. `dense` is the
    # lab's `embedding.dense_size`: d_model on the 512 nets, 512 on the 1024 sponsor net.
    dense = shape.embedding_dense or width
    yield _plan(
        "/attn_body/preproc/w",
        (12 * tokens, tokens * dense),
        embedding.preprocess_weight,
    )
    yield _plan("/attn_body/preproc/b", (tokens * dense,), embedding.preprocess_bias)
    yield _plan(
        "/attn_body/matmul/w",
        (112 + dense, width),
        embedding.embedding_weight,
    )
    yield _plan("/attn_body/matmul/b", (width,), embedding.embedding_bias)
    yield _plan("/attn_body/ln0/scale", (width,), embedding.ln0_scale)
    yield _plan("/attn_body/ln0/bias", (width,), embedding.ln0_bias)
    # The export applies Relu to the gate initializer before multiplying (node 46).
    yield _plan("/attn_body/mult_gate/w", (tokens, width), embedding.input_gate, source="relu")
    yield _plan("/attn_body/position/w", (1, tokens, width), embedding.positional)
    yield from _plan_gated_ffn(
        "/attn_body/ffn",
        width=width,
        hidden=hidden,
        gate=embedding.ffn_gate_weight,
        up=embedding.ffn_up_weight,
        up_bias=embedding.ffn_up_bias,
        down=embedding.ffn_down_weight,
        down_bias=embedding.ffn_down_bias,
        alpha=embedding.ffn_alpha,
    )
    yield _plan("/attn_body/ln1/scale", (width,), embedding.ln1_scale)
    yield _plan("/attn_body/ln1/bias", (width,), embedding.ln1_bias)


def _plan_gated_ffn(  # noqa: PLR0913
    prefix: str,
    *,
    width: int,
    hidden: int,
    gate: str,
    up: str,
    up_bias: str,
    down: str,
    down_bias: str,
    alpha: str,
) -> Iterator[BufferPlan]:
    """Plan one gated FFN as the single wide matrix the fused kernel wants.

    `glu_matmul` reads a `[k, 2n]` matrix with the gate's columns first, so the
    two `[k, n]` projections the export writes separately are interleaved column
    by column here. That is not only what the kernel needs -- it is the cheaper
    form, one wide GEMM against one activation tile instead of two passes over
    the same rows.

    ⚠ The gate projection carries **no bias** in this network: the export's gate
    `Gemm` has two inputs where the up projection's has three. The kernel takes
    one `[2n]` bias, so the gate half is filled with zeros rather than the bias
    being dropped -- an omitted bias and a zero bias are the same function, and
    only one of them survives a shape check.
    """
    padded = padded_hidden(hidden)
    if padded == hidden:
        yield _plan(
            f"{prefix}/dense1/w", (width, 2 * hidden), gate, up, source="gate_pair"
        )
        yield _plan(f"{prefix}/dense1/b", (2 * hidden,), up_bias, source="gate_bias")
        yield _plan(f"{prefix}/dense2/w", (hidden, width), down)
    else:
        yield _plan(f"{prefix}/dense1/w", (width, 2 * padded), gate, up, repr(hidden), source="gate_pair_padded")
        yield _plan(f"{prefix}/dense1/b", (2 * padded,), up_bias, repr(hidden), source="gate_bias_padded")
        yield _plan(f"{prefix}/dense2/w", (padded, width), down, repr(hidden), source="rows_padded")
    yield _plan(f"{prefix}/dense2/b", (width,), down_bias)
    yield _plan(f"{prefix}/alpha/w", (1,), alpha, source="scalar")


def _plan_encoders(network: LabNetwork) -> Iterator[BufferPlan]:
    """Plan every encoder block's projections, norms and static logit tables."""
    shape = network.architecture
    width = shape.d_model
    for index, block in enumerate(network.blocks):
        prefix = encoder_prefix(index)
        if block.gate_weight is not None and output_gate_form() == "packed":
            # O: the output gate reads what Q, K and V read, so it joins the packed projection: [q | k | v | g].
            yield _plan(f"{prefix}/mha/qkvg/w", (width, 4 * width), block.query_weight, block.key_weight,
                        block.value_weight, block.gate_weight, source="concat_columns")
            yield _plan(f"{prefix}/mha/qkvg/b", (4 * width,), block.query_bias, block.key_bias,
                        block.value_bias, block.gate_bias, source="concat")
        else:
            # P3: Q, K and V as one [width, 3 * width] projection, output columns [q | k | v].
            yield _plan(f"{prefix}/mha/qkv/w", (width, 3 * width), block.query_weight, block.key_weight,
                        block.value_weight, source="concat_columns")
            yield _plan(f"{prefix}/mha/qkv/b", (3 * width,), block.query_bias, block.key_bias,
                        block.value_bias, source="concat")
            if block.gate_weight is not None:
                # O, the separate form: the gate as its own [width, width] projection of the same input.
                yield _plan(f"{prefix}/mha/gate/w", (width, width), block.gate_weight)
                yield _plan(f"{prefix}/mha/gate/b", (width,), block.gate_bias)
        yield _plan(f"{prefix}/mha/out/w", (width, width), block.output_weight)
        yield _plan(f"{prefix}/mha/out/b", (width,), block.output_bias)
        yield _plan(
            f"{prefix}/mha/alpha/w", (1,), block.attention_alpha, source="scalar"
        )
        yield _plan(f"{prefix}/ln1/scale", (width,), block.ln1_scale)
        yield _plan(f"{prefix}/ln1/bias", (width,), block.ln1_bias)
        yield from _plan_gated_ffn(
            f"{prefix}/ffn",
            width=width,
            hidden=shape.ffn_hidden,
            gate=block.ffn_gate_weight,
            up=block.ffn_up_weight,
            up_bias=block.ffn_up_bias,
            down=block.ffn_down_weight,
            down_bias=block.ffn_down_bias,
            alpha=block.ffn_alpha,
        )
        yield _plan(f"{prefix}/ln2/scale", (width,), block.ln2_scale)
        yield _plan(f"{prefix}/ln2/bias", (width,), block.ln2_bias)
        if network.egt is not None:
            # R0: an EGT2 block reads 34 edge channels, so the per-code tables of the static path (2**34 codes)
            # do not exist; its logit tables are the folded FP32 set, and the update site follows the block.
            yield from _plan_egt_block(prefix, shape, block, network.egt.blocks[index], network.pair,
                                       network.egt.state_channels)
            site = next((site for site in network.egt.sites if site.after_block == index), None)
            if site is not None:
                yield from _plan_egt_site(prefix, shape, network.egt, site)
            continue
        yield from _plan_logit_tables(prefix, shape, block)
        if network.pair is not None:
            yield from _plan_folds(prefix, shape, block.mix_coefficients, network.pair)
            # P6: the scaled edge term per code, G = C2 @ D^T summed over each code's bits.
            yield _plan(f"{prefix}/pair/scaled_codes", (shape.heads, 1 << shape.edge_channels),
                        block.mix_coefficients, network.pair.channel_mix, source="fold_scaled_codes",
                        data_type=FLOAT32)
        if block.smolgen is not None:
            yield from _plan_smolgen(prefix, shape, block.smolgen, shared=index == 0)


def _plan_smolgen(prefix: str, shape: Architecture, smolgen: SmolgenBlock, *, shared: bool) -> Iterator[BufferPlan]:
    """Plan one block's smolgen chain, and the shared `weight_gen` once (with block 0).

    Weights keep the export's `[in, out]` orientation, as every lab projection does.
    """
    channels, hidden = shape.smolgen_channels, shape.smolgen_hidden
    generated = shape.heads * shape.smolgen_gen
    yield _plan(f"{prefix}/smolgen/compress/w", (shape.d_model, channels), smolgen.compress_weight)
    yield _plan(f"{prefix}/smolgen/dense1/w", (shape.tokens * channels, hidden), smolgen.dense1_weight)
    yield _plan(f"{prefix}/smolgen/dense1/b", (hidden,), smolgen.dense1_bias)
    yield _plan(f"{prefix}/smolgen/ln1/scale", (hidden,), smolgen.ln1_scale)
    yield _plan(f"{prefix}/smolgen/ln1/bias", (hidden,), smolgen.ln1_bias)
    yield _plan(f"{prefix}/smolgen/dense2/w", (hidden, generated), smolgen.dense2_weight)
    yield _plan(f"{prefix}/smolgen/dense2/b", (generated,), smolgen.dense2_bias)
    yield _plan(f"{prefix}/smolgen/ln2/scale", (generated,), smolgen.ln2_scale)
    yield _plan(f"{prefix}/smolgen/ln2/bias", (generated,), smolgen.ln2_bias)
    if shared:
        yield _plan(
            "/smolgen/weight_gen/w", (shape.smolgen_gen, shape.tokens * shape.tokens), smolgen.weight_gen
        )


def _plan_logit_tables(prefix: str, shape: Architecture, block: object) -> Iterator[
    BufferPlan
]:
    """Plan the four learned tables that bias the scores before the softmax.

    The leading `1` the export gives each table is dropped: it is a broadcast
    placeholder for the batch, and an artifact buffer is not batched. Keeping it
    would make the shape check pass for the wrong reason.
    """
    heads, edges, depth = shape.heads, shape.edge_channels, shape.head_dim
    yield _plan(
        f"{prefix}/mha/edge/coefficients", (heads, edges), block.edge_coefficients
    )
    yield _plan(f"{prefix}/mha/edge/key", (heads, edges, depth), block.pair_key)
    yield _plan(f"{prefix}/mha/edge/query", (heads, edges, depth), block.pair_query)
    # P6: per-code FP32 tables for attention_static's gather form, folded from the FP16 tables above.
    codes = 1 << edges
    yield _plan(f"{prefix}/mha/edge/query_codes", (heads, depth, codes), block.pair_query,
                source="code_table", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/edge/key_codes", (heads, depth, codes), block.pair_key,
                source="code_table", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/edge/coefficient_codes", (heads, codes), block.edge_coefficients,
                source="code_sums", data_type=FLOAT32)
    if block.mix_coefficients is not None:
        yield _plan(
            f"{prefix}/mha/mix/coefficients",
            (heads, shape.mix_channels),
            block.mix_coefficients,
        )


def _plan_heads(network: LabNetwork) -> Iterator[BufferPlan]:
    """Plan the value, policy and moves-left output heads."""
    heads = network.heads
    shape = network.architecture
    width, tokens = shape.d_model, shape.tokens
    value_width = 128
    moves_width = 8
    wdl = 3

    yield _plan("/value/embedding/w", (width, value_width), heads.value_square_weight)
    yield _plan("/value/embedding/b", (value_width,), heads.value_square_bias)
    yield _plan(
        "/value/dense1/w",
        (tokens * value_width, value_width),
        heads.value_hidden_weight,
    )
    yield _plan("/value/dense1/b", (value_width,), heads.value_hidden_bias)
    yield _plan("/value/dense2/w", (value_width, wdl), heads.value_output_weight)
    yield _plan("/value/dense2/b", (wdl,), heads.value_output_bias)

    # The policy head's own width (`shared_policy_embedding_size`, and the served head's `d_model`): d_model on the
    # 512 nets, 512 on the 1024 sponsor net.
    policy = shape.policy_width or width
    yield _plan(
        "/policy/embedding/w", (width, policy), heads.policy_embedding_weight
    )
    yield _plan("/policy/embedding/b", (policy,), heads.policy_embedding_bias)
    yield _plan("/policy/Q/w", (policy, policy), heads.policy_query_weight)
    yield _plan("/policy/Q/b", (policy,), heads.policy_query_bias)
    yield _plan("/policy/K/w", (policy, policy), heads.policy_key_weight)
    yield _plan("/policy/K/b", (policy,), heads.policy_key_bias)
    yield _plan(
        "/policy/promotion/w", (policy, 4), heads.policy_promotion_weight
    )
    if heads.policy_mix_coefficients is not None and network.pair is not None:
        yield _plan(
            "/policy/mix/coefficients",
            (shape.mix_channels,),
            heads.policy_mix_coefficients,
        )
        # The export divides QK^T + bias together (node 4230): the bias folds carry the divisor.
        yield from _plan_folds("/policy", shape, heads.policy_mix_coefficients, network.pair, heads=1,
                               divisor=network.policy_divisor)
    yield _plan(
        "/policy/map/w",
        (1858,),
        heads.policy_map,
        source="integer",
        data_type=INT32,
    )

    yield _plan("/moves/embedding/w", (width, moves_width), heads.moves_square_weight)
    yield _plan("/moves/embedding/b", (moves_width,), heads.moves_square_bias)
    yield _plan(
        "/moves/dense1/w",
        (tokens * moves_width, value_width),
        heads.moves_hidden_weight,
    )
    yield _plan("/moves/dense1/b", (value_width,), heads.moves_hidden_bias)
    yield _plan("/moves/dense2/w", (value_width, 1), heads.moves_output_weight)
    yield _plan("/moves/dense2/b", (1,), heads.moves_output_bias)


def _plan_pair(network: LabNetwork) -> Iterator[BufferPlan]:
    """Plan the two pair-stream tables the prologue kernel reads.

    Both are FLOAT32: the lab RMS-norms the pair stream in f32
    (`pair_stream._rmsnorm`) and so does the export, so the prologue computes
    `S` from f32 constants and stores only the result in FP16.
    """
    shape = network.architecture
    if network.pair is None:
        # No pair stream: the prologue still builds E, and computes S from zero tables
        # that nothing reads. 16 is `prologue_static.PAIR_CHANNELS`, fixed in the kernel.
        yield _plan("/prologue/channel_mix", (shape.edge_channels, 16), source="zeros", data_type=FLOAT32)
        yield _plan("/prologue/offsets", (16, shape.tokens, shape.tokens), source="zeros", data_type=FLOAT32)
    elif network.egt is not None:
        # R0: K1's five FP32 tables (the pair stream over 34 channels, the edge-stream seed and their code sums).
        if (shape.edge_channels, shape.mix_channels, network.egt.state_channels) != (
            EGT_EDGE_CHANNELS, 16, EGT_STATE_CHANNELS
        ):
            message = (
                f"EGT2 prologue: {shape.edge_channels} edge, {shape.mix_channels} pair and "
                f"{network.egt.state_channels} state channels; prologue_egt is built for "
                f"{EGT_EDGE_CHANNELS}, 16 and {EGT_STATE_CHANNELS}"
            )
            raise ValueError(message)
        prologue = network.egt.prologue
        yield from plan_prologue_egt(
            channel_mix=network.pair.channel_mix,
            offset_table=network.pair.offset_table,
            edge_mix=prologue.edge_mix,
            edge_offset_table=prologue.edge_offset_table,
            relative_index=prologue.relative_index,
        )
    else:
        yield from _plan_pair_tables(network)
    # No initializer holds the score scale: the export divides by a scalar.
    yield _plan(
        "/encoder/qk_scale",
        (1,),
        repr(network.blocks[0].attention_scale),
        source="constant",
    )
    # The policy logits are unscaled in the export, but `policy_qk` always
    # multiplies by a scale buffer.
    yield _plan("/policy/qk_scale", (1,), repr(1.0 / network.policy_divisor), source="constant")


def _plan_pair_tables(network: LabNetwork) -> Iterator[BufferPlan]:
    """Plan the pair stream's two prologue tables from the export."""
    shape = network.architecture
    yield _plan(
        "/prologue/channel_mix",
        (shape.edge_channels, shape.mix_channels),
        network.pair.channel_mix,
        data_type=FLOAT32,
    )
    yield _plan(
        "/prologue/offsets",
        (shape.mix_channels, shape.tokens, shape.tokens),
        network.pair.offset_table,
        network.pair.relative_index,
        source="offsets",
        data_type=FLOAT32,
    )


def _plan_folds(
    prefix: str,
    shape: Architecture,
    mix_coefficients: str,
    pair: PairTables,
    *,
    heads: int | None = None,
    divisor: float = 1.0,
) -> Iterator[BufferPlan]:
    """Plan the two build-time folds of one consumer of the pair stream.

    `sum_t C2[h,t] M[t] = S (sum_e G[h,e] E[e] + K[h])` with `G = C2 @ D^T` and
    `K = einsum(C2, T)` (`attention_static.fold_scaled_coefficients` /
    `fold_constant_bias`). A block has 32 heads; the policy head is one.
    """
    count = shape.heads if heads is None else heads
    yield _plan(
        f"{prefix}/pair/scaled_coefficients",
        (count, shape.edge_channels),
        mix_coefficients,
        pair.channel_mix,
        *(() if divisor == 1.0 else (repr(divisor),)),
        source="fold_scaled",
    )
    yield _plan(
        f"{prefix}/pair/constant_bias",
        (count, shape.tokens, shape.tokens),
        mix_coefficients,
        pair.offset_table,
        pair.relative_index,
        *(() if divisor == 1.0 else (repr(divisor),)),
        source="fold_bias",
    )


# ---------------------------------------------------------------- R0 (item E, round 20c): EGT2 blocks and sites
# Every table the logit assembly, the gate or an update site reads is FP32 (item E map section 5.3: FP16 logit
# assembly adds ~50 % to H's error); the projections stay FP16, as on the static path. Channel maps are planned
# as `[out, in]`, `y[o] = sum_c W[o, c] x[c]`: the block reads are exported that way, the site and triplet maps
# are exported transposed and flipped here (source "transpose").


def _plan_egt_block(  # noqa: PLR0913
    prefix: str, shape: Architecture, block: EncoderBlock, edge: EgtBlock, pair: PairTables, states: int,
) -> Iterator[BufferPlan]:
    """Plan one EGT2 block's folded logit tables (the map's section 5.1 folds, in float64, stored FP32).

    `H = (QK' + sum_c C1'[h,c] E[c] + (k.P_k')E + (q.P_q')E + S (G.E + K') + sum_c We'[h,c] e[c])
    (1 + sum_c Wm[h,c] e[c])`, then `A = softmax(H) min(2 sigmoid(Wg.e + g_b), 1)` (the cap only on a capped
    export): `t_node` is folded into every static term, `t_edge` into the edge read.
    """
    heads, edges, depth, tokens = shape.heads, shape.edge_channels, shape.head_dim, shape.tokens
    node, edge_temperature = edge.node_temperature, edge.edge_temperature
    yield _plan(f"{prefix}/mha/egt/qk_scale", (heads,), node, repr(block.attention_scale),
                source="head_scaled_constant", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/attack", (heads, edges), node, block.edge_coefficients,
                source="head_scaled", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/key", (heads, edges, depth), node, block.pair_key,
                source="head_scaled", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/query", (heads, edges, depth), node, block.pair_query,
                source="head_scaled", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/scaled_coefficients", (heads, edges), block.mix_coefficients, pair.channel_mix,
                node, source="egt_fold_scaled", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/constant_bias", (heads, tokens, tokens), block.mix_coefficients,
                pair.offset_table, pair.relative_index, node, source="egt_fold_bias", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/edge_read/w", (heads, states), edge_temperature, edge.edge_read,
                source="head_scaled", data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/door/w", (heads, states), edge.door, data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/gate/w", (heads, states), edge.gate_weight, data_type=FLOAT32)
    yield _plan(f"{prefix}/mha/egt/gate/b", (heads,), edge.gate_bias, data_type=FLOAT32)


def _plan_egt_site(prefix: str, shape: Architecture, egt: EgtNetwork, site: EgtSite) -> Iterator[BufferPlan]:
    """Plan the update site after one block: readback, the optional triplet, then the edge FFN (all FP32).

    `e_hat = e + O_e H`; with a triplet `e_hat += W_o (va_in | va_out)` from `rms(e_hat)` through `W_v` and
    `W_g, b_g`; then `e' = rms(e_hat + W_2 relu(W_1 rms(e_hat) + b_1))`.
    """
    heads, states, hidden = shape.heads, egt.state_channels, egt.site_hidden
    site_prefix = f"{prefix}/edge_site"
    yield _plan(f"{site_prefix}/readback/w", (states, heads), site.readback_weight, source="transpose",
                data_type=FLOAT32)
    if site.triplet is not None:
        triplet = site.triplet
        yield _plan(f"{site_prefix}/triplet/value/w", (2 * states, states), triplet.value_weight, source="transpose",
                    data_type=FLOAT32)
        yield _plan(f"{site_prefix}/triplet/gate/w", (states, states), triplet.gate_weight, source="transpose",
                    data_type=FLOAT32)
        yield _plan(f"{site_prefix}/triplet/gate/b", (states,), triplet.gate_bias, data_type=FLOAT32)
        yield _plan(f"{site_prefix}/triplet/out/w", (states, 2 * states), triplet.output_weight, source="transpose",
                    data_type=FLOAT32)
    yield _plan(f"{site_prefix}/ffn/dense1/w", (hidden, states), site.ffn_in_weight, source="transpose",
                data_type=FLOAT32)
    yield _plan(f"{site_prefix}/ffn/dense1/b", (hidden,), site.ffn_in_bias, data_type=FLOAT32)
    if site.ffn_rev_weight is not None:
        # `rev_edge`: the second in-projection, read against rms(e_hat)[j, i] (`edge_site.REVERSE_TABLE`).
        yield _plan(f"{site_prefix}/ffn/dense1_rev/w", (hidden, states), site.ffn_rev_weight, source="transpose",
                    data_type=FLOAT32)
    yield _plan(f"{site_prefix}/ffn/dense2/w", (states, hidden), site.ffn_out_weight, source="transpose",
                data_type=FLOAT32)
